= Movies Service API Guide
Billy Korando;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[resources-tag-retrieve]]
=== Get all movies

A `GET` request will retrieve the details of a tag

operation::find-all-movies[snippets='response-fields,curl-request,http-response,response-fields']

=== Add movie

A `POST` request will retrieve the details of a tag

operation::add-movie[snippets='request-fields,response-fields,curl-request,http-response']

=== Find movies by genre and run length

A `GET` request will retrieve the details of a tag

operation::find-movies-by-genre-run-length[snippets='request-fields,response-fields,curl-request,http-response']

=== Find movies by name

A `GET` request will retrieve the details of a tag

operation::find-movies-by-name[snippets='request-fields,response-fields,curl-request,http-response']

=== Find movies by title

A `GET` request will retrieve the details of a tag

operation::find-movies-by-title[snippets='request-fields,response-fields,curl-request,http-response']